kind: Pod
apiVersion: v1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  hostNetwork: true
  containers:
    # Runs calico/node container on each Kubernetes node.  This
    # container programs network policy and routes on each
    # host.
    - name: calico-node
      image: quay.io/calico/node:v2.5.1
      env:
        # The location of the Calico etcd cluster.
        - name: ETCD_ENDPOINTS
          value: "${ETCD_ENDPOINTS}"
        # Choose the backend to use.
        - name: CALICO_NETWORKING_BACKEND
          value: "bird"
        # Disable file logging so `kubectl logs` works.
        - name: CALICO_DISABLE_FILE_LOGGING
          value: "true"
        # Set Felix endpoint to host default action to ACCEPT.
        - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
          value: "ACCEPT"
        # The Calico IPv4 pool to use.  This should match `--cluster-cidr`
        - name: CALICO_IPV4POOL_CIDR
          value: "${CLUSTER_CIDR}"
        # Enable IPIP
        - name: CALICO_IPV4POOL_IPIP
          value: "cross-subnet"
        # Disable IPv6 on Kubernetes.
        - name: FELIX_IPV6SUPPORT
          value: "false"
        # Set Felix logging to "info"
        - name: FELIX_LOGSEVERITYSCREEN
          value: "info"
        # Enable IP-in-IP within Felix.
        - name: FELIX_IPINIPENABLED
          value: "true"
        # Set based on the k8s node name.
        - name: NODENAME
          value: "${IP}"
        # Auto-detect the BGP IP address.
        - name: IP
          value: "${IP}"
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 250m
      volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /var/run/calico
          name: var-run-calico
          readOnly: false
  volumes:
    # Used by calico/node.
    - name: lib-modules
      hostPath:
        path: /lib/modules
    - name: var-run-calico
      hostPath:
        path: /var/run/calico
