[template]
src = "pods.tmpl"
dest = "/etc/confd/hosts/pods"
prefix = "/registry"
keys = [
    "/pods",
    "/namespaces"
]

check_cmd = "dnsmasq --test"
reload_cmd = "killall -SIGHUP dnsmasq || true"
