[template]
src = "services.tmpl"
dest = "/etc/confd/hosts/services"
prefix = "/registry"
keys = [
    "/services/specs",
    "/services/endpoints",
    "/namespaces"
]

check_cmd = "dnsmasq --test"
reload_cmd = "killall -SIGHUP dnsmasq || true"
