[template]
src = "services.tmpl"
dest = "/etc/confd/hosts/services"
prefix = "/registry/services"
keys = [
    "/specs/default",
    "/endpoints/default"
]

check_cmd = "dnsmasq --test"
reload_cmd = "killall -SIGHUP dnsmasq || true"
