apiVersion: v1
kind: Config
clusters:
- name: kubernetes
  cluster:
    server: $KUBERNETES_MASTER
    insecure-skip-tls-verify: true
users:
- name: kubelet
contexts:
- context:
    cluster: kubernetes
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
